AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless REST API application for Approach Winners
Globals:
  Function:
    Runtime: python3.12
    Timeout: 60
    Tracing: Active
    MemorySize: 1024
    Tags:
      Project: Winners
  Api:
    Auth:
      UsagePlan:
        UsagePlanName: DailyUsagePlan
        CreateUsagePlan: PER_API
        Description: This will limit 5000 executions per day and throttle executions
          on 10% of that.
        Quota:
          Limit: 5000
          Period: DAY
        Throttle:
          BurstLimit: 20
          RateLimit: 10
Parameters:
  VersionParam:
    Type: String
    Default: v1
  StageNameParam:
    Type: String
    Default: prod
Resources:
  ApproachEndpointApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ApproachEndpointApi
      StageName:
        Ref: StageNameParam
      TracingEnabled: true
      Cors:
        AllowOrigin: '''*'''
        AllowMethods: '''GET,POST,OPTIONS'''
        AllowHeaders: '''Content-Type,X-Amz-Date,X-Amz-Security-Token,Authorization,X-Api-Key,X-Requested-With,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'''
      MethodSettings:
      - DataTraceEnabled: true
        MetricsEnabled: true
        HttpMethod: '*'
        ResourcePath: /*
        LoggingLevel: INFO
      AccessLogSetting:
        DestinationArn:
          Fn::Sub: arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${ApiAccessLogGroup}
        Format: $context.identity.sourceIp $context.authorizer.claims.sub [$context.requestTime]
          "$context.httpMethod $context.resourcePath $context.protocol" $context.status
          $context.requestId $context.awsEndpointRequestId $context.xrayTraceId $context.responseLatency
          $context.integrationLatency "$context.error.message"
    Metadata:
      SamResourceId: ApproachEndpointApi
  PythonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: s3://approach/api-approach/c2526d296ddac6dfec46eb13f4dcd1ea
      CompatibleRuntimes:
      - python3.12
    Metadata:
      BuildMethod: makefile
      SamResourceId: PythonLayer
  ApproachFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://approach/api-approach/c0f27805cbf42f7473b951b900eb667e
      Handler: handler.list_subscriptions
      Tracing: Active
      Role: arn:aws:iam::992382506739:role/Approach-ReadGoogleSheetRole
      Events:
        GetItem:
          Type: Api
          Properties:
            Path: /list
            Method: POST
            RestApiId:
              Ref: ApproachEndpointApi
    Metadata:
      SamResourceId: ApproachFunction
  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/apigateway/AccessLog-${ApproachEndpointApi}
      RetentionInDays: 365
    Metadata:
      SamResourceId: ApiAccessLogGroup
Outputs:
  ApproachEndpointFunctionApi:
    Description: API Gateway endpoint URL for Approach Arena Winners Prod stage
    Value:
      Fn::Sub: https://${ApproachEndpointApi}.execute-api.${AWS::Region}.amazonaws.com/{StageNameParam}
